CREATE TABLE WINLOSS (
  ID INT PRIMARY KEY NOT NULL,
  RANKING VARCHAR(25) NOT NULL,
  COLLEGE VARCHAR(25) NOT NULL,
  WIN VARCHAR(25) NOT NULL,
  LOSS VARCHAR(25) NOT NULL,
  PCT VARCHAR(25) NOT NULL   
);


