CREATE TABLE winLossPercent(
  ID SERIAL PRIMARY KEY,
  YEAR INTEGER NOT NULL,
  TEAM_NAME VARCHAR(64) NOT NULL,
  NUM_WINS INTEGER NOT NULL,
  NUM_LOSSES INTEGER NOT NULL,
  WIN_PERCENTAGE DECIMAL(7,5) NOT NULL
);

CREATE TABLE offensiveScoring(
  ID SERIAL PRIMARY KEY,
  YEAR INTEGER NOT NULL,
  TEAM_NAME VARCHAR(64) NOT NULL,
  NUM_GAMES INTEGER NOT NULL,
  NUM_POINTS INTEGER NOT NULL,
  AVG_POINTS_PER_GAME DECIMAL (7,5) NOT NULL
);

CREATE TABLE defensiveScoring(
  ID SERIAL PRIMARY KEY,
  YEAR INTEGER NOT NULL,
  TEAM_NAME VARCHAR(64) NOT NULL,
  NUM_GAMES INTEGER NOT NULL,
  NUM_OPPONENT_POINTS INTEGER NOT NULL,
  AVG_OPPONENT_POINTS_PER_GAME DECIMAL (7,5) NOT NULL
);

CREATE TABLE scoringMargin(
  ID SERIAL PRIMARY KEY,
  YEAR INTEGER NOT NULL,
  TEAM_NAME VARCHAR(64) NOT NULL,
  NUM_GAMES INTEGER NOT NULL,
  NUM_POINTS INTEGER NOT NULL,
  NUM_OPPONENT_POINTS INTEGER NOT NULL,
  SCORING_MARGIN_PER_GAME DECIMAL (7,5) NOT NULL,
  SCORING_MARGIN_SEASON INTEGER NOT NULL
);

CREATE TABLE fieldGoalPercent(
  ID SERIAL PRIMARY KEY,
  YEAR INTEGER NOT NULL,
  TEAM_NAME VARCHAR(64) NOT NULL,
  NUM_GAMES INTEGER NOT NULL,
  NUM_FG_MADE INTEGER NOT NULL,
  NUM_FG_PER_GAME DECIMAL (7,5) NOT NULL,
  NUM_FG_ATTEMPTS INTEGER NOT NULL,
  NUM_FG_ATTEMPTS_PER_GAME DECIMAL (7,5) NOT NULL,
  FG_PERCENTAGE DECIMAL (7,5) NOT NULL
);

CREATE TABLE fieldGoalPercentDefense(
  ID SERIAL PRIMARY KEY,
  YEAR INTEGER NOT NULL,
  TEAM_NAME VARCHAR(64) NOT NULL,
  NUM_GAMES INTEGER NOT NULL,
  NUM_OPP_FG_MADE INTEGER NOT NULL,
  NUM_OPP_FG_ATTEMPTS INTEGER NOT NULL,
  NUM_OPP_FG_PER_GAME DECIMAL (7,5) NOT NULL,
  NUM_OPP_FG_ATTEMPTS_PER_GAME DECIMAL (7,5) NOT NULL,
  OPP_FG_PERCENTAGE DECIMAL (7,5) NOT NULL
);

CREATE TABLE threePointsPerGame(
  ID SERIAL PRIMARY KEY,
  YEAR INTEGER NOT NULL,
  TEAM_NAME VARCHAR(64) NOT NULL,
  NUM_GAMES INTEGER NOT NULL,
  NUM_3P_MADE INTEGER NOT NULL,
  NUM_3P_PER_GAME DECIMAL (7,5) NOT NULL
);

CREATE TABLE threePointPercentage(
  ID SERIAL PRIMARY KEY,
  YEAR INTEGER NOT NULL,
  TEAM_NAME VARCHAR(64) NOT NULL,
  NUM_GAMES INTEGER NOT NULL,
  NUM_3P_MADE INTEGER NOT NULL,
  NUM_3P_ATTEMPTS INTEGER NOT NULL,
  NUM_3P_PER_GAME DECIMAL (7,5) NOT NULL,
  NUM_3P_ATTEMPTS_PER_GAME DECIMAL (7,5) NOT NULL,
  T3P_PERCENTAGE DECIMAL (7,5) NOT NULL
);

CREATE TABLE threePointPercentageDefense(
  ID SERIAL PRIMARY KEY,
  YEAR INTEGER NOT NULL,
  TEAM_NAME VARCHAR(64) NOT NULL,
  NUM_GAMES INTEGER NOT NULL,
  NUM_OPP_3P_MADE INTEGER NOT NULL,
  NUM_OPP_3P_ATTEMPTS INTEGER NOT NULL,
  NUM_OPP_3P_PER_GAME DECIMAL (7,5) NOT NULL,
  NUM_OPP_3P_ATTEMPTS_PER_GAME DECIMAL (7,5) NOT NULL,
  OPP_3P_PERCENTAGE DECIMAL (7,5) NOT NULL
);

CREATE TABLE freeThrowPercentage(
  ID SERIAL PRIMARY KEY,
  YEAR INTEGER NOT NULL,
  TEAM_NAME VARCHAR(64) NOT NULL,
  NUM_GAMES INTEGER NOT NULL,
  NUM_FT_MADE INTEGER NOT NULL,
  NUM_FT_ATTEMPTS INTEGER NOT NULL,
  NUM_FT_PER_GAME DECIMAL (7,5) NOT NULL,
  NUM_FT_ATTEMPTS_PER_GAME DECIMAL (7,5) NOT NULL,
  FT_PERCENTAGE DECIMAL (7,5) NOT NULL
);

CREATE TABLE reboundMargin(
  ID SERIAL PRIMARY KEY,
  YEAR INTEGER NOT NULL,
  TEAM_NAME VARCHAR(64) NOT NULL,
  NUM_GAMES INTEGER NOT NULL,
  NUM_REBOUNDS INTEGER NOT NULL, 
  REBOUNDS_PER_GAME DECIMAL(7,5), 
  OPP_NUM_REBOUNDS INTEGER NOT NULL, 
  OPP_REBOUNDS_PER_GAME DECIMAL(7,5), 
  REBOUND_MARGIN DECIMAL (7,5) NOT NULL
);

CREATE TABLE assistsPerGame(
  ID SERIAL PRIMARY KEY,
  YEAR INTEGER NOT NULL,
  TEAM_NAME VARCHAR(64) NOT NULL,
  NUM_GAMES INTEGER NOT NULL,
  NUM_ASSISTS INTEGER NOT NULL,
  ASSISTS_PER_GAME DECIMAL (7,5) NOT NULL
);

CREATE TABLE assistTurnoverRatio(
  ID SERIAL PRIMARY KEY,
  YEAR INTEGER NOT NULL,
  TEAM_NAME VARCHAR(64) NOT NULL,
  NUM_GAMES INTEGER NOT NULL,
  NUM_ASSISTS INTEGER NOT NULL,
  NUM_TURNOVERS INTEGER NOT NULL,
  ATO_RATIO DECIMAL (7,5) NOT NULL
);

CREATE TABLE blocksPerGame (
  ID SERIAL PRIMARY KEY,
  YEAR INTEGER NOT NULL,
  TEAM_NAME VARCHAR(64) NOT NULL,
  NUM_GAMES INTEGER NOT NULL,
  NUM_BLOCKS INTEGER NOT NULL,
  BLOCKS_PER_GAME DECIMAL (7,5) NOT NULL
);

CREATE TABLE stealsPerGame (
  ID SERIAL PRIMARY KEY,
  YEAR INTEGER NOT NULL,
  TEAM_NAME VARCHAR(64) NOT NULL,
  NUM_GAMES INTEGER NOT NULL,
  NUM_STEALS INTEGER NOT NULL,
  STEALS_PER_GAME DECIMAL (7,5) NOT NULL
);

CREATE TABLE turnoversPerGame (
  ID SERIAL PRIMARY KEY,
  YEAR INTEGER NOT NULL,
  TEAM_NAME VARCHAR(64) NOT NULL,
  NUM_GAMES INTEGER NOT NULL,
  NUM_TURNOVERS INTEGER NOT NULL,
  turnoversPerGame DECIMAL (7,5) NOT NULL
);

CREATE TABLE turnoverMargin(
  ID SERIAL PRIMARY KEY,
  YEAR INTEGER NOT NULL,
  TEAM_NAME VARCHAR(64) NOT NULL,
  NUM_GAMES INTEGER NOT NULL,
  NUM_TURNOVERS INTEGER NOT NULL, 
  TURNOVERS_PER_GAME DECIMAL(7,5), 
  OPP_NUM_TURNOVERS INTEGER NOT NULL, 
  OPP_TURNOVERS_PER_GAME DECIMAL(7,5), 
  TURNOVER_MARGIN DECIMAL (7,5) NOT NULL
);

CREATE TABLE foulsPerGame (
  ID SERIAL PRIMARY KEY,
  YEAR INTEGER NOT NULL,
  TEAM_NAME VARCHAR(64) NOT NULL,
  NUM_GAMES INTEGER NOT NULL,
  NUM_FOULS INTEGER NOT NULL,
  FOULS_PER_GAME DECIMAL (7,5) NOT NULL,
  NUM_DQ INTEGER NOT NULL
);

CREATE TABLE tournament(
  ID SERIAL PRIMARY KEY,
  YEAR INTEGER NOT NULL,
  GAME_DATE DATE NOT NULL,
  WINNING_TEAM_NAME VARCHAR(64) NOT NULL,
  WINNING_SCORE INTEGER NOT NULL,
  LOSING_TEAM_NAME VARCHAR(64) NOT NULL,
  LOSING_SCORE INTEGER NOT NULL
);